flags: {}

extra-include-dirs:
- /usr/local/include

extra-lib-dirs:
- /usr/local/lib

packages:
- '.'
- ../hep-utilities
- ../lhco-tools
- ../lhef-tools
- ../hs-mt2calculator
extra-deps: []
resolver: lts-3.8
